const programs = [
  { icon: 'Aa', title: 'Curious Classrooms', text: 'Strong foundations in language, maths and science—taught through questions, stories and discovery.' },
  { icon: '✦', title: 'Creative Expression', text: 'Art, music, dance and theatre help every child find their voice and build confidence.' },
  { icon: '🌱', title: 'Roots & Values', text: 'Festivals, local traditions and everyday kindness keep our children connected to culture and community.' },
];

export default function Home() {
  return <main>
    <header className="site-header"><a className="brand" href="#top" aria-label="DreamHigh Public School home"><img className="brand-logo" src="/dreamhigh-logo-enhanced.png" alt="DreamHigh Public School logo" /><span><strong>DreamHigh</strong><small>Public School · Waraseoni</small></span></a><nav aria-label="Main navigation"><a href="#about">Our Story</a><a href="#principal">Principal</a><a href="#learning">Learning</a><a href="#life">School Life</a><a href="#contact">Contact</a></nav><a className="header-cta" href="#contact">Visit us <span>↗</span></a></header>
    <section className="hero" id="top"><div className="hero-copy"><p className="eyebrow"><span /> Growing curious minds since 2012</p><h1>Big dreams begin in <em>happy</em> classrooms.</h1><p className="hero-intro">A close-knit school in Waraseoni where 200 young learners discover, create and grow—with strong roots in culture and learning that feels like play.</p><div className="hero-actions"><a className="primary-btn" href="#about">Discover our school <span>→</span></a><a className="text-link" href="#contact">Admissions enquiry</a></div><div className="hero-note"><div className="avatar-stack"><span>🎨</span><span>📚</span><span>🌱</span></div><p><strong>200 little dreamers</strong><br />One caring school family</p></div></div><div className="hero-visual"><div className="hero-photo"><img src="/dreamhigh-classroom.png" alt="Primary school children enjoying an art activity with their teacher" /><span>Learning is an adventure</span></div><div className="doodle doodle-one">✦</div><div className="doodle doodle-two">〰</div><div className="floating-card"><span>☀</span><p><strong>Learn. Laugh.</strong><br />Dream high.</p></div></div></section>
    <section className="promise-strip" aria-label="Our school values"><p>Kind hearts</p><span>✦</span><p>Curious minds</p><span>✦</span><p>Strong roots</p><span>✦</span><p>Bright futures</p></section>
    <section className="story section" id="about"><div><p className="section-kicker">A school that feels like home</p><h2>Small in size.<br /><em>Big on possibility.</em></h2></div><div className="story-copy"><p className="lead">Since 2012, DreamHigh has been a place where children are known by name, teachers know every family, and learning goes far beyond a textbook.</p><p>Our consistent academic results come from patient teaching, personal attention and the belief that a child learns best when they feel safe, seen and excited to come to school.</p><a className="arrow-link" href="#learning">How we help children grow <span>→</span></a></div><div className="stats"><div><strong>2012</strong><span>our journey began</span></div><div><strong>200</strong><span>students in our family</span></div><div><strong>1:20</strong><span>personal teacher attention</span></div></div></section>
    <section className="principal section" id="principal"><div className="principal-photo"><img src="/principal-photo.png" alt="Principal of DreamHigh Public School" /></div><div className="principal-message"><p className="section-kicker">From the Principal’s desk</p><h2>A message from <em>our Principal</em></h2><p className="principal-text">At DreamHigh, we believe every child carries a spark of brilliance waiting to be discovered. Our role is simple yet sacred—to nurture that spark with patience, love and the right guidance. When children feel valued and happy, learning follows naturally. This is the promise we make to every family that joins us.</p><p className="principal-name">— <strong>Mrs. Ranu Dubey</strong><br /><span>Principal, DreamHigh Public School</span></p></div></section>
    <section className="learning section" id="learning"><div className="section-heading"><p className="section-kicker">The DreamHigh way</p><h2>Learning that <em>sticks</em>—<br />because it feels like fun.</h2><p>We balance strong academics with the experiences that shape thoughtful, confident human beings.</p></div><div className="program-grid">{programs.map((program, i) => <article className={`program-card card-${i + 1}`} key={program.title}><span className="program-icon">{program.icon}</span><p>0{i + 1}</p><h3>{program.title}</h3><div className="card-art">{i === 0 ? '📖' : i === 1 ? '🎭' : '🪔'}</div><p className="card-copy">{program.text}</p></article>)}</div></section>
    <section className="day section" id="life"><div className="day-card"><div className="day-copy"><p className="section-kicker light">A day at DreamHigh</p><h2>Every day brings a new reason to <em>smile.</em></h2><p>Morning circles, lively lessons, playground friendships, story time, art, sports and celebration—school days here are full of little moments that become big memories.</p><a className="light-link" href="#contact">Come see us in action <span>↗</span></a></div><div className="day-collage"><div className="collage-main"><img src="/dreamhigh-classroom.png" alt="Children learning together in a lively classroom" /></div><div className="quote-card"><span>“</span><p>Children remember how learning made them feel.</p></div><div className="sunburst">☀</div></div></div></section>
    <section className="results section"><p className="section-kicker">Growing with confidence</p><h2>Steady results.<br /><em>Stronger children.</em></h2><div className="result-grid"><article><span>01</span><h3>Consistent academics</h3><p>Dependable performance since 2012, built on clear concepts and individual support.</p></article><article><span>02</span><h3>Confident communicators</h3><p>Activities, assemblies and performance give every child the courage to speak and share.</p></article><article><span>03</span><h3>Good human beings</h3><p>Respect, responsibility and compassion are part of every lesson and every school day.</p></article></div></section>
    <section className="contact section" id="contact"><div className="contact-panel"><div><p className="section-kicker light">Admissions open</p><h2>Let your child’s<br /><em>dream take flight.</em></h2><p>Come meet our teachers, walk through our classrooms and feel the warmth of our school community.</p></div><div className="contact-details"><a href="tel:+917566270818"><span>Call us</span><strong>+91 75662 70818</strong></a><a href="mailto:dreamhighpublicschool32@gmail.com"><span>Email us</span><strong>dreamhighpublicschool32@gmail.com</strong></a><div><span>Find us</span><strong>Waraseoni, Balaghat<br />Madhya Pradesh</strong></div></div></div></section>
    <footer><a className="brand footer-brand" href="#top"><img className="brand-logo footer-logo" src="/dreamhigh-logo-enhanced.png" alt="DreamHigh Public School logo" /><span><strong>DreamHigh</strong><small>Public School · Waraseoni</small></span></a><p>Nurturing kind hearts & curious minds since 2012.</p><a href="#top">Back to top ↑</a></footer>
  </main>;
}
